// eslint.config.js
import js from '@eslint/js';
import globals from 'globals';
import { defineConfig, globalIgnores } from 'eslint/config';
import eslintPluginN from 'eslint-plugin-n';
import eslintPlugin from 'eslint-plugin-eslint-plugin';
import eslintPluginJsdoc from 'eslint-plugin-jsdoc';
import eslintPluginEslintComments from 'eslint-plugin-eslint-comments';
import prettierConfig from 'eslint-config-prettier';
import prettierPlugin from 'eslint-plugin-prettier/recommended';

export default defineConfig([
	js.configs.recommended,
	eslintPluginN.configs['flat/recommended-module'],
	eslintPlugin.configs.recommended,
	eslintPluginJsdoc.configs['flat/recommended'],
	globalIgnores(['node_modules/', 'dist/', '.pnp.*', 'yarn.lock', '.yarn/*', '.git/', 'coverage/']),
	{
		files: ['**/*.{js,mjs,cjs}'],
		plugins: {
			'eslint-plugin': eslintPlugin,
			jsdoc: eslintPluginJsdoc,
			'eslint-comments': eslintPluginEslintComments,
		},
		languageOptions: { globals: globals.node },
		rules: {
			// Code quality
			'no-console': 'error',
			'no-debugger': 'error',
			'no-var': 'error',
			'prefer-const': 'error',
			'prefer-arrow-callback': 'error',
			'array-callback-return': ['error', { checkForEach: true }],
			'no-constructor-return': 'error',
			'no-duplicate-imports': ['error', { includeExports: true, allowSeparateTypeImports: false }],
			'no-empty-pattern': ['error', { allowObjectPatternsAsParameters: true }],
			'no-promise-executor-return': 'error',
			'no-self-compare': 'error',
			'no-template-curly-in-string': 'error',
			'no-unassigned-vars': 'error',
			'no-unmodified-loop-condition': 'error',
			'no-unsafe-negation': 'error',
			'no-use-before-define': 'error',
			'no-useless-assignment': 'error',
			'require-atomic-updates': 'error',
			'accessor-pairs': 'error',
			'arrow-body-style': ['error', 'as-needed'],
			'block-scoped-var': 'error',
			camelcase: 'error',
			'capitalized-comments': 'error',
			'consistent-return': 'error',
			'consistent-this': ['error', 'this'],
			curly: ['error', 'multi'],
			'default-case': 'error',
			'default-case-last': 'error',
			'default-param-last': 'error',
			'dot-notation': 'error',
			eqeqeq: 'error',
			'func-names': ['error', 'always'],
			'func-style': ['error', 'declaration'],
			'grouped-accessor-pairs': ['error', 'getBeforeSet'],
			'guard-for-in': 'error',
			'logical-assignment-operators': ['error', 'never'],
			'max-depth': ['error', 3],
			'max-nested-callbacks': ['error', 2],
			'no-array-constructor': 'error',
			'no-bitwise': 'warn',
			'no-caller': 'error',
			'no-div-regex': 'error',
			'no-else-return': 'error',
			'no-empty-function': 'error',
			'no-eq-null': 'error',
			'no-eval': 'error',
			'no-extra-bind': 'error',
			'no-implicit-coercion': 'error',
			'no-implied-eval': 'error',
			'no-invalid-this': 'error',
			'no-iterator': 'error',
			'no-lone-blocks': 'error',
			'no-lonely-if': 'error',
			'no-loop-func': 'error',
			'no-multi-assign': 'error',
			'no-multi-str': 'error',
			'no-nested-ternary': 'error',
			'no-new': 'error',
			'no-new-func': 'error',
			'no-new-wrappers': 'error',
			'no-object-constructor': 'error',
			'no-octal-escape': 'error',
			'no-param-reassign': 'error',
			'no-plusplus': 'error',
			'no-proto': 'error',
			'no-return-assign': 'error',
			'no-sequences': 'error',
			'no-shadow': 'error',
			'no-throw-literal': 'error',
			'no-undef-init': 'error',
			'no-undefined': 'off', // Useless since ES5
			'no-underscore-dangle': 'error',
			'no-unneeded-ternary': 'error',
			'no-unused-expressions': 'error',
			'no-useless-call': 'error',
			'no-useless-computed-key': 'error',
			'no-useless-concat': 'error',
			'no-useless-constructor': 'error',
			'no-useless-rename': 'error',
			'no-useless-return': 'error',
			'no-void': 'error',
			'no-warning-comments': [
				'warn',
				{ terms: ['todo', 'fixme', 'tofix', 'fix', 'debug'], location: 'anywhere' },
			],
			'object-shorthand': 'error',
			'operator-assignment': 'error',
			'prefer-named-capture-group': 'error',
			'prefer-object-has-own': 'error',
			'prefer-object-spread': 'error',
			'prefer-regex-literals': 'error',
			'prefer-rest-params': 'error',
			'prefer-spread': 'error',
			'prefer-template': 'error',
			'preserve-caught-error': 'error',
			radix: 'error',
			'require-await': 'error',
			'symbol-description': 'error',
			'vars-on-top': 'error',
			'no-magic-numbers': 'off',

			// Style
			indent: ['error', 2],
			quotes: ['error', 'single', { avoidEscape: true }],
			semi: ['error', 'always'],
			'comma-dangle': ['error', 'never'],
			'object-curly-spacing': ['error', 'always'],
			'array-bracket-spacing': ['error', 'never'],

			// ESLint Plugin specific rules
			'eslint-plugin/prefer-placeholders': 'error',
			'eslint-plugin/require-meta-docs-recommended': 'error',
			'eslint-plugin/require-meta-docs-url': 'error',
			'eslint-plugin/no-unused-message-ids': 'error',

			// JSDoc rules
			'jsdoc/require-description': 'warn',
			'jsdoc/require-param-description': 'warn',
			'jsdoc/require-returns': 'warn',
			'jsdoc/require-jsdoc': 'warn',
			'jsdoc/check-param-names': 'warn',
			'jsdoc/check-tag-names': 'warn',
			'jsdoc/no-undefined-types': 'warn',
			'jsdoc/require-param': 'warn',
			'jsdoc/require-param-type': 'warn',
			'jsdoc/require-returns-type': 'warn',

			// ESLint comments rules
			...eslintPluginEslintComments.configs.recommended.rules,
			'eslint-comments/no-unused-disable': 'error',
			'eslint-comments/no-duplicate-disable': 'error',
			'eslint-comments/require-description': 'warn',
		},
	},
	{
		files: ['tests/**/*.{js,mjs,cjs}'],
		languageOptions: {
			globals: {
				...globals.node,
				describe: 'readonly',
				it: 'readonly',
				before: 'readonly',
				after: 'readonly',
			},
		},
		rules: { 'no-console': 'off' },
	},
	// Override base config with prettier rules
	prettierConfig,
	prettierPlugin,
]);
